# filebeat.yml
filebeat.inputs:
  - type: filestream
    id: suricata-logs
    enabled: true
    paths:
      - /var/log/suricata/eve.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"] 

setup.kibana:
  host: "http://kibana:5601"           # URL di Kibana per configurazioni automatiche

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

setup.template.enabled: true
setup.template.overwrite: true
setup.template.name: "filebeat-suricata"
setup.template.pattern: "filebeat-suricata-*"

logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
